---
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
preserve_hierarchy: true
files:
  - source: /custom_components/myskoda/translations/en.json
    translation: /custom_components/myskoda/translations/%two_letters_code%.json
